<?php

/**
 * @file
 * Authorize.net - UI
 */

/* ******************************************************************************
 * Form functions
 * *****************************************************************************/

/**
 * User billing add/edit form.
 */
function authnet_ui_billing_form($form_state, $user) {

  // Set the form up as a tree.
  $form = array(
    '#tree' => TRUE,
  );

  // Billing fieldset.
  $form['billing'] = array(
    '#type' => 'fieldset',
    '#title' => t('Billing address'),
  );
  $form['billing']['customer_type'] = array(
    '#type' => 'select',
    '#title' => t('Customer type'),
    '#options' => array(
      '' => '',
      'individual' => 'Individual',
      'business' => 'Business',
    ),
  );
  $form['billing']['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#required' => TRUE,
  );
  $form['billing']['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#required' => TRUE,
  );
  $form['billing']['company'] = array(
    '#type' => 'textfield',
    '#title' => t('Company'),
  );
  $form['billing']['address'] = array(
    '#type' => 'textfield',
    '#title' => t('Address'),
    '#required' => TRUE,
  );
  $form['billing']['city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#required' => TRUE,
  );
  $form['billing']['state'] = array(
    '#type' => 'textfield',
    '#title' => t('State/province'),
    '#required' => TRUE,
  );
  $form['billing']['zip'] = array(
    '#type' => 'textfield',
    '#title' => t('Zip/postal code'),
    '#required' => TRUE,
  );
  $form['billing']['country'] = array(
    '#type' => 'textfield',
    '#title' => t('Country'),
    '#required' => TRUE,
  );
  $form['billing']['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone'),
  );
  $form['billing']['fax'] = array(
    '#type' => 'textfield',
    '#title' => t('Fax'),
  );

  // Credit card fieldset.
  $form['card'] = array(
    '#type' => 'fieldset',
    '#title' => t('Card information'),
  );
  $form['card']['type'] = array(
    '#type' => 'select',
    '#title' => t('Card type'),
    '#options' => array(
      'visa' => 'Visa',
      'mastercard' => 'MasterCard',
      'american_express' => 'American Express',
      'discover' => 'Discover',
    ),
    '#required' => TRUE,
  );
  $form['card']['number'] = array(
    '#type' => 'textfield',
    '#title' => t('Card number'),
    '#required' => TRUE,
  );
  $form['card']['exp_month'] = array(
    '#type' => 'select',
    '#title' => t('Expiration month'),
    '#options' => array(
      '01',
      '02',
      '03',
      '04',
      '05',
      '06',
      '07',
      '08',
      '09',
      '10',
      '11',
      '12',
    ),
    '#required' => TRUE,
  );

  // Build a list of year options (current year + 10).
  $years = array();
  $current_year = date('Y');
  for ($year=$current_year;$year<=($current_year+10);$year++) {
    $years[] = $year;
  }
  $form['card']['exp_year'] = array(
    '#type' => 'select',
    '#title' => t('Expiration year'),
    '#options' => $years,
    '#required' => TRUE,
  );

  $form['card']['cvv'] = array(
    '#type' => 'textfield',
    '#title' => t('Card CVV'),
    '#size' => 5,
    '#required' => TRUE,
  );

  // Save button.
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

/* ******************************************************************************
 * Helper functions
 * *****************************************************************************/

/**
 * Generate a list of payment profile options
 *
 * @param $customer_profile
 *   A customer profile object
 *
 * @return
 *   An array of options usable as form radio options
 */
function authnet_ui_payment_profile_options($customer_profile) {
  $options = array();
  foreach ($customer_profile->paymentProfiles as $payment_profile) {
    // At the moment we're only adding credit card payment profiles.
    if (!empty($payment_profile->payment->creditCard->cardNumber)) {

      // Add an option to the array with the last four digits and the street address.
      $options[$payment_profile->customerPaymentProfileId] = t('Credit card: ' . $payment_profile->payment->creditCard->cardNumber . ' (' . $payment_profile->billTo->address . ')');
    }
  }
  return $options;
}