<?php

/**
 * @file
 * Authorize.net - User Integration
 */

/* ******************************************************************************
 * Drupal hooks
 * *****************************************************************************/

/* ******************************************************************************
 * Authnet hooks
 * *****************************************************************************/

/**
 * Implementation of hook_authnet_cim_profile_insert().
 */
function authnet_user_authnet_cim_profile_insert($customerProfile) {
  if (!empty($customerProfile->merchantCustomerId)) {
    authnet_user_profile_id_save($customerProfile->merchantCustomerId, $customerProfile->customerProfileId);
  }
}

/**
 * Implementation of hook_authnet_cim_profile_delete().
 */
function authnet_user_authnet_cim_profile_delete($customerProfileId) {
  authnet_user_profile_id_delete($customerProfileId);
}

/* ******************************************************************************
 * User profile id functions
 * *****************************************************************************/

/**
 * Get a customer profile id, based on a user id.
 *
 * @param $uid
 *   The Drupal user id.
 *
 * @return
 *   Returns the Authorize.net customer profile id for the given user id, if available. FALSE otherwise.
 */
function authnet_user_profile_id_load($uid) {

  // Look up the customer profile id.
  return db_result(db_query('SELECT customer_profile_id FROM {authnet_user} WHERE uid=%d', $uid));
}

/**
 * Save a user's customer profile id to the database.
 *
 * @param $uid
 *   The Drupal user id.
 * @param $customer_profile_id
 *   The Authorize.net customer profile id.
 */
function authnet_user_profile_id_save($uid, $customer_profile_id) {

  // Build the record.
  $record = array(
    'uid' => $uid,
    'customer_profile_id' => $customer_profile_id,
  );

  // Write the record.
  drupal_write_record('authnet_user', $record);
}

/**
 * Delete a customer profile id from the database.
 *
 * @param $customer_profile_id
 *   The Authorize.net customer profile id.
 */
function authnet_user_profile_id_delete($customer_profile_id) {

  // Delete the profile id.
  db_query('DELETE FROM {authnet_user} WHERE customer_profile_id=%d', $customer_profile_id);
}