<?php

/**
 * @file
 * Authorize.net - Ubercart Integration
 * A replacement for uc_authorizenet. Process payments using Authorize.net 
 */

/* ******************************************************************************
 * Drupal hooks
 * *****************************************************************************/

/**
 * Implementation of hook_form_alter().
 */
function authnet_uc_form_alter(&$form, &$form_state, $form_id) {

  // Alter the credit card terminal form in the order admin interface (/admin/store/orders/%order-id/credit)
  if ($form_id == 'uc_credit_terminal_form') {

    // Load the order.
    // Bail if no order or if order doesn't have a user
    $order = uc_order_load($form['order_id']['#value']);
    if (empty($order) || empty($order->uid)) return;

    // Load the customer profile from Authorize.net.
    // Bail if the customer profile doesn't have payment profiles...
    $customer_profile = authnet_cim_entity_profile_load('user', $order->uid);
    if (empty($customer_profile->paymentProfiles)) return;

    // Set the weight of the 'amount' field so that it is at the top.
    $form['amount']['#weight'] = -2;

    // Create a new fieldset for the existing payment profiles.
    $form['authnet_payment_profiles'] = array(
      '#type' => 'fieldset',
      '#title' => t('Existing payment profiles'),
      '#description' => t('This order\'s customer has the following payment profiles.'),
      '#weight' => -1,
    );

    $form['authnet_payment_profiles']['payment_profile'] = array(
      '#type' => 'radios',
      '#options' => authnet_ui_payment_profile_options($customer_profile),
    );

    // Buttons
    $form['authnet_payment_profiles']['authorize'] = array(
      '#type' => 'submit',
      '#value' => t('Charge amount to this profile'),
    );
  }
}

/**
 * Implements hook_theme().
 */
function authnet_uc_theme() {
  return array(
    'authnet_uc_payment_method_credit_checkout_form' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/* ******************************************************************************
 * Ubercart hooks
 * *****************************************************************************/

/**
 * Implementation of hook_payment_gateway().
 */
function authnet_uc_payment_gateway() {
  $gateways[] = array(
    'id' => 'authnet',
    'title' => t('Authorize.net'),
    'description' => t('Process credit card payments using Authorize.net.'),
    'settings' => 'authnet_uc_settings_form',
    'credit' => 'authnet_uc_charge',
    'credit_txn_types' => array(UC_CREDIT_AUTH_ONLY, UC_CREDIT_PRIOR_AUTH_CAPTURE, UC_CREDIT_AUTH_CAPTURE, UC_CREDIT_REFERENCE_SET, UC_CREDIT_REFERENCE_TXN),
  );

  return $gateways;
}

/**
 * Implementation of hook_payment_method_alter().
 */
function authnet_uc_payment_method_alter(&$methods) {

  /**
   * Replace the callback function of the 'credit' payment method with our own.
   * We do this so that we can offer users the ability to choose an existing card.
   * See authnet_uc_payment_method_credit() below.
   */
  if (!empty($methods)) {
    foreach ($methods as &$method) {
      if ($method['id'] == 'credit') {

        // Replace the callback function with our own.
        $method['callback'] = 'authnet_uc_payment_method_credit';

        // Stop the foreach loop.
        break;
      }
    }
  }
}

/* ******************************************************************************
 * Forms
 * *****************************************************************************/

/**
 * Payment gateway settings form.
 */
function authnet_uc_settings_form() {
  module_load_include('inc', 'authnet_uc', 'includes/authnet_uc.pages');
  return _authnet_uc_settings_form();
}

/**
 * Credit payment method checkout form.
 */
function authnet_uc_payment_method_credit_checkout_form($form_state, $order, $customer_profile) {

  // Get the list of payment profile options for this customer.
  $options = authnet_ui_payment_profile_options($customer_profile);

  // Add an option for setting up a new card.
  $options['new'] = t('Add a new card...');

  // Display the list of radio buttons.
  $form['select'] = array(
    '#type' => 'radios',
    '#title' => t('Choose an existing credit card or add a new one:'),
    '#options' => $options,
    '#required' => TRUE,
    '#default_value' => 'new',
  );

  // Append the old uc_payment_method_credit_form().
  $form += uc_payment_method_credit_form($form_state, $order);

  // Return the form.
  return $form;
}

/* ******************************************************************************
 * Theme functions
 * *****************************************************************************/

/**
 * Themes the "add a credit card" form to be in a compact table.
 */
function theme_authnet_uc_payment_method_credit_checkout_form($form) {

  // Render the radio select list.
  $output = drupal_render($form['select']);

  // Pass-through to the original theme_uc_payment_method_credit_form().
  $output .= theme_uc_payment_method_credit_form($form);

  // Return the rendered form.
  return $output;
}

/* ******************************************************************************
 * Callbacks
 * *****************************************************************************/

/**
 * Callback for payment gateway settings.
 */
function authnet_uc_charge($order_id, $amount, $data) {
  module_load_include('inc', 'authnet_uc', 'includes/authnet_uc.charge');
  return _authnet_uc_charge($order_id, $amount, $data);
}

/**
 * Replacement callback for the credit payment method.
 * The goal of this function is to act as a simple wrapper around the uc_credit's normal payment method callback: uc_payment_method_credit().
 * This function is called first, does the stuff it needs to do, and in most cases passes the call of to uc_payment_method_credit().
 *
 * See authnet_uc_payment_method_alter() above.
 */
function authnet_uc_payment_method_credit($op, &$arg1, $silent = FALSE) {

  // If the $op is 'cart-details' it means we're rendering the checkout form.
  if ($op == 'cart-details') {

    // Get information about the current user.
    global $user;

    // If the user is logged in and has a customer profile...
    if ($user->uid && $customer_profile = authnet_cim_entity_profile_load('user', $user->uid)) {

      // Return our custom form, stripped for Ubercart's checkout form.
      $details = drupal_get_form('authnet_uc_payment_method_credit_checkout_form', $arg1, $customer_profile);
      return uc_strip_form($details);
    }
  }

  // If the above code hasn't returned something already, pass-through to to original uc_payment_method_credit() function.
  return uc_payment_method_credit($op, $arg1, $silent);
}